### ISSUE TITLE
Add Medium articles section

### ISSUE THREAD

**Issue by bombnp** [fivechjr/thinc-www#70]
Connect Thinc's articles in medium and put it in website.

Thinc's Medium: https://medium.com/thinc-org

**Comment by new5558** [comment]
Should we use medium's RSS feed API then convert to JSON
https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/thinc-org

**Comment by bombnp** [comment]
please assign yourself if and when you decide to work on it so we can track

**Comment by new5558** [comment]
Should we?
1. fetch API on client-side
2. fetch API on CI and built the static site based on it

**Comment by bombnp** [comment]
if we build on CI, that would mean new articles won't appear though? unless we rerun CI

**Comment by new5558** [comment]
> if we build on CI, that would mean new articles won't appear though? unless we rerun CI

Yes, but we only publish few articles per year, and as you can see from the [API](https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/thinc-org), the payload is large and contains unnecessary `description` and `content` (We may need only first sentence from `description`). This may create a bottleneck when page load because client side have to do the following things:
1. Fetch large RSS
2. Convert to JSON
3. Sanitize/Clean html in each article's content
4. Render React element

**Comment by bombnp** [comment]
i suppose we could schedule github actions workflows to rebuild the site every day or something
